homework1
Valtersen/Homework pull request #1
Opened 2021-04-12 18:29 UTC by Valtersen

test solution

2021-04-14 13:12 UTC, serhii-shkodenko requested changes
В целом задание почти выполнено. Из существенного - нужно подкорректировать логику определения суммы после скидки.

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +            int l = destinations.Count();
Используй неявное определение типа для переменной. Здесь можно [почитать детальнее](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#implicitly-typed-local-variables).

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +            if (l != clients.Count() || l != prices.Count()||l!=currencies.Count())
Коллекцию адресов тоже стоит включить в проверку.

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +            decimal[] NewPrices=new decimal[l];
Локальные переменные именуются в `camelCase`.

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +            decimal[] NewPrices=new decimal[l];
Используй неявное определение типа для переменной. Здесь можно [почитать детальнее](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#implicitly-typed-local-variables).

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +            //Стоимость доставки увеличивается на 10 долларов, если доставка осуществляется по Wayne Street.
Комментарии лучше всего писать на английском языке. Есть [требования конвенции, как их оформлять](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#commenting-conventions).

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +//            3.Стоимость доставки уменьшается на 25 %, если клиент -ребенок.
Комментарии лучше всего писать на английском языке. Есть [требования конвенции, как их оформлять](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#commenting-conventions).

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +                        NewPrices[i] -=decimal.Multiply(NewPrices[i],0.15m);
Ты здесь посчитала скидку, а не цену после скидки. Нужно еще отнять сумму скидуи от цены.

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +                NewPrices[n] -= decimal.Multiply(NewPrices[n], 0.25m);
Ты здесь посчитала скидку, а не цену после скидки. Нужно еще отнять сумму скидуи от цены.

2021-04-14 13:12 UTC, serhii-shkodenko commented on HomeWork.cs
> +                NewPrices[n] -= decimal.Multiply(NewPrices[n], 0.50m);
Ты здесь посчитала скидку, а не цену после скидки. Нужно еще отнять сумму скидуи от цены.

2021-04-15 22:26 UTC, Valtersen commented on HomeWork.cs
> +            if (l != clients.Count() || l != prices.Count()||l!=currencies.Count())
Тут проверяются остальные коллекции относительно коллекции адресов, или проверять все ко всему нужно?

2021-04-15 22:31 UTC, serhii-shkodenko commented on HomeWork.cs
> +            if (l != clients.Count() || l != prices.Count()||l!=currencies.Count())
Ты права, здесь все ок. Все, что нужно, ты проверила. Не увидел, что количество элементов в массиве адресов ты в переменную записала. Переменную `l` лучше назвать `destinationsCount`.

2021-04-15 22:37 UTC, Valtersen commented on HomeWork.cs
> +            decimal[] NewPrices=new decimal[l];
Не очень понимаю как здесь применить неявное определение типа, если создается массив и инициализируется позже

2021-04-15 22:39 UTC, serhii-shkodenko commented on HomeWork.cs
> +            decimal[] NewPrices=new decimal[l];
Вот так можно
`var newPrices = new decimal[l];`

2021-04-15 22:40 UTC, Valtersen commented on HomeWork.cs
> +            decimal[] NewPrices=new decimal[l];
а хорошо спасибо

2021-04-16 15:04 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-04-16 18:30 UTC, merged