Delivery Classes
Valtersen/Homework pull request #2
Opened 2021-04-22 23:09 UTC by Valtersen

assignment 1&2

2021-04-27 11:20 UTC, serhii-shkodenko requested changes

2021-04-27 11:20 UTC, serhii-shkodenko commented on ClassConsoleExtensions.cs
> +    class ClassConsoleExtensions
Не хватает модификатора доступа.

2021-04-27 11:20 UTC, serhii-shkodenko commented on ClassConsoleExtensions.cs
> +    class ClassConsoleExtensions
Этот класс не содержить методов расширения, поэтому должен быть назвать без слова `Extensions`. Его наличие противоречит общепринятой конвенции.

2021-04-27 11:20 UTC, serhii-shkodenko commented on Clients.cs
> +    public class BussinesClient : Client
Каждый отдельный класс лучше размещать в отдельном файле. Это способствует хорошей органзиации кода.

2021-04-27 11:20 UTC, serhii-shkodenko commented on Clients.cs
> +    public class ConsumerClient : Client
Каждый отдельный класс лучше размещать в отдельном файле. Это способствует хорошей органзиации кода.

2021-04-27 11:20 UTC, serhii-shkodenko commented on Clients.cs
> +    public class ConsumerClient : Client
Этот класс делаешь слишком много. У него несколько задач, что противоречит Single responsibility principle.

2021-04-27 11:20 UTC, serhii-shkodenko commented on Clients.cs
> +    public class BussinesClient : Client
Этот класс делаешь слишком много. У него несколько задач, что противоречит Single responsibility principle.

2021-04-27 11:20 UTC, serhii-shkodenko commented on ClassConsoleExtensions.cs
> +
Лучше удалить эти пустые строки.

2021-04-28 12:53 UTC, Valtersen commented on ClassConsoleExtensions.cs
> +    class ClassConsoleExtensions
А куда можно добавить методы для отображения информации, о заказе или меню например, в сами классы с меню и клиентами? или можно просто переименовать класс?

2021-05-04 20:42 UTC, serhii-shkodenko requested changes

2021-05-04 20:42 UTC, serhii-shkodenko commented on ClassConsoleExtensions.cs
> +    class ClassConsoleExtensions
Для этого лучше создать отдельный класс по работе с пользовательским интерфейсом и там разместить эти методы. Такому методу в качестве зависимости нужно передать класс для работы с бизнес логикой, не забывая при этом про Dependency inversion principle.

2021-05-20 22:33 UTC, serhii-shkodenko commented
1. Пожалуйста, комментарии, которые ты исправила, пометь, как исправленные. Для этого служит кнопка "Resolve conversation". Я об этом говорил на встречах. Также об этом указано в требованиях к гит флоу, которые были опубликованы в канале курсов одновременно с их началом, документ показывался вам на первом занятии. 
2. В упомянутом документе также было отмечено, что для каждого задания создается отдельный пулл реквест. Ты же с последними изменениями залила в этот ПР все задания с 2 по 5.
3. Удали, пожалуйста, все файлы, которые не относятся ко второму заданию. 
4. Выполненные задания оформь в отдельные ПР.

2021-05-26 19:28 UTC, Valtersen commented on Program.cs
> +            foreach (var item in bob.cart.Products)
item? but the name "product" is already used in line 14

2021-05-26 19:28 UTC, Valtersen commented on Clients/BussinesClient.cs
> +        public Menu menu= new();
Business clients can add products that consumers can order (add to cart), added products are in their menu. If i understood the question right.

2021-06-02 17:20 UTC, yevhenbilushko commented on Clients/Clients.cs
> +        public static void RegisterClient(Client client)
add line before ctor

2021-06-02 17:20 UTC, yevhenbilushko commented on Clients/Clients.cs
> +            T client;
seems like it can be 
return (T)ClientBase.SingleOrDefault(T => T.Name == name);

2021-06-02 17:20 UTC, yevhenbilushko commented on Clients/Client.cs
> +        public Client(string name)
add line before ctor and before method everywhere

2021-06-02 17:20 UTC, yevhenbilushko commented on Clients/Clients.cs
> +            T client;
in other places as well

2021-06-02 17:20 UTC, yevhenbilushko commented on Clients/ConsumerClient.cs
> +            Name = name;
seems like you can remove it cause you do it in base ctor
as well as for other "Client" derived classes

2021-06-02 17:20 UTC, yevhenbilushko commented on Products/Cart.cs
> +        public void AddProduct(Product product)
add lines between methods

2021-06-02 17:20 UTC, yevhenbilushko commented on Products/Cart.cs
> +        public decimal fullPrice = 0;
seems like it can be revomed 
itis 0 by default

2021-06-02 17:20 UTC, yevhenbilushko commented on Products/Menu.cs
> +        public void AddProduct(Product product)
add line before ctor

2021-06-02 17:20 UTC, yevhenbilushko commented on Clients/BusinessClient.cs
> +namespace DeliveryService
please double check branches "main" and "Delivery-Service-Types"
i cloned it to local and can not run

2021-06-03 22:29 UTC, serhii-shkodenko commented
Удали, пожалуйста, из ПР все файлы, которые не относятся ко второму заданию. Оставь здесь только модели.

2021-06-05 08:20 UTC, serhii-shkodenko requested changes
Пожалуйста, оставь в ПР только классы, моделирующие твою предметную область.

2021-06-05 08:20 UTC, serhii-shkodenko commented on Products/Cart.cs
> +    public class Cart
Этот класс не модель, а класс из слоя бизне логики. Он должен быть третьем задании.

2021-06-05 08:20 UTC, serhii-shkodenko commented on Products/Menu.cs
> +    public class Menu
Это тоже класс реализующий бизнес логику, не модель.

2021-06-05 22:27 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-06-06 14:27 UTC, merged

2021-06-10 16:29 UTC, serhii-shkodenko commented
Ты почему-то создала пулл реквест в Delivery-Service-Types, а вне в main. Создай, пожалуйста, пулл реквест в мейн.

2021-06-10 19:08 UTC, Valtersen commented
Пересоздала PR

чт, 10 июн. 2021 г. в 19:29, Sergiy ***@***.***>:

> Ты почему-то создала пулл реквест в Delivery-Service-Types, а вне в main.
> Создай, пожалуйста, пулл реквест в мейн.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Valtersen/Homework/pull/2#issuecomment-858767816>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARDZMAQT2C7A6QN2ZBWFGNLTSDR5ZANCNFSM43NQXLSQ>
> .
>