Revert 2 delivery classes (assignment 2)
Valtersen/Homework pull request #4
Opened 2021-06-10 19:06 UTC by Valtersen

2021-06-10 19:10 UTC, serhii-shkodenko requested changes

2021-06-10 19:10 UTC, serhii-shkodenko commented on HomeWork.cs
> -using System.Collections.Generic;
Первое задание не нужно удалять.

2021-06-10 19:13 UTC, Valtersen commented on HomeWork.cs
> -using System.Collections.Generic;
тогда создать отдельные папки под них получается?

2021-06-11 21:10 UTC, serhii-shkodenko requested changes

2021-06-11 21:10 UTC, serhii-shkodenko commented on a2/Products/Menu.cs
> +    public class Menu
Это не модель. Этого класса не должно быть во втором ПР.

2021-06-11 21:10 UTC, serhii-shkodenko commented on a2/Products/Cart.cs
> +    public class Cart
Это не модель. Этого класса не должно быть во втором ПР.

2021-06-11 21:10 UTC, serhii-shkodenko commented on a2/Clients/ConsumerClient.cs
> +    public class ConsumerClient : Client
Это не модель. Этого класса не должно быть во втором ПР.

2021-06-11 21:10 UTC, serhii-shkodenko commented on a2/Clients/Clients.cs
> +    public static class Clients
Это не модель. Этого класса не должно быть во втором ПР.

2021-06-11 21:10 UTC, serhii-shkodenko commented on a2/Clients/Client.cs
> +    public abstract class Client
Это не модель. Этого класса не должно быть во втором ПР.

2021-06-11 21:10 UTC, serhii-shkodenko commented on a2/Clients/BusinessClient.cs
> +    public class BusinessClient : Client
Это не модель. Этого класса не должно быть во втором ПР.

2021-06-11 21:55 UTC, merged